name: FFmpeg Stream Processing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ffmpeg_stream:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up FFmpeg
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      # Process M3U8 Stream and send to Facebook Live RTMP Server
      - name: Process M3U8 Stream to Facebook Live
        run: |
          ffmpeg -i "https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8" -c copy -f flv "rtmp://live-api-s.facebook.com:80/rtmp/FB-1295634538294049-0-AbxnM15DLKbKiHlJ"
